name: Color Change Automation

on:
  push:
    branches:
      - development  # Run workflow on pushes to development branch

jobs:
  change-color:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Node20 compatible by default

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Node20 compatible version
        with:
          flutter-version: "3.0.0"  # Adjust Flutter version as needed

      - name: Run color change script
        run: |
          chmod +x ./color_change.sh   # Make the script executable
          ./color_change.sh   
          
      - name: Commit color changes
        run: |
          git config --local user.name "priyanshumanash"
          git config --local user.email "luvitpriyanshu@gmail.com"
          git add lib/main.dart        # Add the modified file
          git commit -m "Updated primary and secondary colors"
          git push origin main         # Push the changes back to the repository
     
