name: Change Colors on Push

on:
  push:
    branches:
      - main

jobs:
  change_colors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Run color change script
        run: |
          chmod +x change_colors.sh
          ./change_colors.sh

      - name: Commit changes
        run: |
          git config --local user.email "luvitpriyanshu@gmail.com"
          git config --local user.name "Priyanshu Manash"
          git add lib/main.dart
          git commit -m "Update colors to random values" || echo "No changes to commit"
          git push
