name: Color Change Automation

on:
  push:
    branches:
      - main  # Run the workflow when pushing to the main branch

jobs:
  change-color:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"  # Specify your Flutter version here

      - name: Run color change script
        run: |
          chmod +x ./color_change.sh   # Make the script executable
          ./color_change.sh            # Run the script

      - name: Commit color changes
        run: |
          git config --local user.name "priyanshumanash"
          git config --local user.email "luvitpriyanshu@gmail.com"
          git add lib/main.dart        # Add the modified file
          git commit -m "Updated primary and secondary colors"
          git push origin main         # Push the changes back to the repository
