name: Change Colors on Push

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  change-colors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'  # Use your specific Flutter version

      - name: Make script executable
        run: chmod +x ./change_colors.sh

      - name: Run color change script
        run: ./change_colors.sh
          git push

      - name: Commit changes
        run: |
          git config --local user.email "luvitpriyanshu@gmail.com"
          git config --local user.name "Priyanshu Manash"
          git add lib/main.dart
          git commit -m "Update colors to random values" || echo "No changes to commit"
          git push
